FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
      curl \
      jq \
      git \
      unzip \
      ca-certificates \
      docker.io

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" \
    -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip

RUN docker --version
RUN aws --version
RUN jq --version